# Generated by Django 5.2.17 on 2026-08-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_assigned_employee_student_fee_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='students/aadhaar/'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
    ]
