# Generated by Django 5.2.17 on 2026-08-24 08:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('INR', '₹ INR - Indian Rupee'), ('USD', '$ USD - US Dollar'), ('EUR', '€ EUR - Euro'), ('GBP', '£ GBP - British Pound'), ('AED', 'د.إ AED - UAE Dirham'), ('CAD', '$ CAD - Canadian Dollar'), ('AUD', '$ AUD - Australian Dollar'), ('SGD', '$ SGD - Singapore Dollar')], default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='project_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('india', 'Indian'), ('foreigner', 'Foreigner')], default='india', max_length=20),
        ),
    ]
