# Generated by Django 5.2.17 on 2026-08-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_currency_project_project_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('indian', 'Indian'), ('foreigner', 'Foreigner')], default='indian', max_length=20),
        ),
    ]
