# Generated by Django 5.2.17 on 2026-08-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_development_cost_project_project_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='developer_cost',
        ),
    ]
