# Generated by Django 5.2.17 on 2026-08-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_task_options_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='employee_comment',
            field=models.TextField(blank=True, default='', help_text='Comment/update provided by the assigned employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='remaining_days',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate number of days remaining to complete the task', null=True),
        ),
    ]
