# Generated by Django 5.2.17 on 2026-09-01 05:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='paid_development_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
