# Generated by Django 5.2.17 on 2026-09-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_project_paid_development_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='development_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
