# Generated by Django 5.2.17 on 2026-09-01 08:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_student_course_duration_months_studentfeepayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfeepayment',
            options={'ordering': ['payment_month'], 'verbose_name': 'Student Fee Payment', 'verbose_name_plural': 'Student Fee Payments'},
        ),
        migrations.RemoveField(
            model_name='studentfeepayment',
            name='monthly_fee',
        ),
        migrations.AddField(
            model_name='student',
            name='certificate_status',
            field=models.CharField(choices=[('not_issued', 'Not Issued'), ('issued', 'Certificate Issued')], default='not_issued', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='course_duration_days',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', to='core.student'),
        ),
        migrations.AddIndex(
            model_name='studentfeepayment',
            index=models.Index(fields=['student', 'payment_month'], name='core_studen_student_a26c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeepayment',
            index=models.Index(fields=['student', 'status'], name='core_studen_student_5a848d_idx'),
        ),
    ]
