# Generated by Django 5.2.17 on 2026-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_chatmessage_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
