# Generated by Django 5.2.17 on 2026-09-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_userstatus_is_online_userstatus_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='last_seen',
        ),
    ]
